name: Quality Check

on:
  push:
  pull_request:
    branches: [ main ]


permissions:
  contents: write
  pull-requests: write
  repository-projects: write


jobs:
  # Single deploy job since we're just deploying
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm ci
      - name: Eslint
        run: npm run eslint
      - name: Type Checking
        run: npm run tsc
      - name: Test
        run: npm run test
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
