name: Quality Check

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install 🔧
        run: npm ci
      - name: Eslint
        run: npm run eslint
      - name: Type Checking
        run: npm run tsc
      - name: Test
        run: npm run test
