name: Quality Check

on:
  push:
  pull_request:
    branches: [ main ]

env:
  tag: '0.0.10'


permissions:
  contents: write
  pull-requests: write
  repository-projects: write


jobs:
  # Single deploy job since we're just deploying
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm ci
      - name: Eslint
        run: npm run eslint
      - name: Type Checking
        run: npm run tsc
      - name: Test
        run: npm run test
